name: CI Automation Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Chrome browser
        uses: browser-actions/setup-chrome@v1.7.3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Web UI tests
        run: |
          ./gradlew runWebTests \
            -Dcucumber.filter.tags="@web" \
            -Dcucumber.plugin=html:build/reports/cucumber/web/html \
            -Dcucumber.plugin=json:build/reports/cucumber/web/json/cucumber.json

      - name: Run API tests
        run: |
          ./gradlew runApiTests \
            -Dcucumber.filter.tags="@api" \
            -Dcucumber.plugin=html:build/reports/cucumber/api/html \
            -Dcucumber.plugin=json:build/reports/cucumber/api/json/cucumber.json

      - name: Upload Web HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-html-report
          path: build/reports/cucumber/web/html/index.html

      - name: Upload Web JSON report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-json-report
          path: build/reports/cucumber/web/json/cucumber.json

      - name: Upload API HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-html-report
          path: build/reports/cucumber/api/html/index.html

      - name: Upload API JSON report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-json-report
          path: build/reports/cucumber/api/json/cucumber.json
